name: Actualizar Flashcards

on:
  schedule:
    - cron: '/5 * * * *'  # Cada d√≠a a las 6 AM
  workflow_dispatch:    # Permite ejecutar manualmente desde GitHub UI

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Instalar requests
        run: pip install requests
      - name: Ejecutar script
        run: python generate_json.py
      - name: Subir cambios
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Actualizar data.json desde Google Sheets"
